---
title: "Milestone #2"
author: "Aisha Abdelhamid"
date: "9/25/2020"
output: html_document
---
Github repo with Rmd (and knitted html) which discusses pros and cons two projects from past years. At least one project should be one which did extensive data gathering/cleaning. You should not select the same projects for commentary as your friends have. Students generally write about a paragraph for each project. The Rmd/html file should include the url for your repo. The only thing you are submitting is the html, via Canvas.

[Link to markdown cheatsheet](https://github.com/aishaabdelhamid/milestone_2)

## State of the Union Text Analysis by Will Schrepferman

Screpferman's project seems to do a great deal of text analysis and data 
collection. One thing that I would improve about his project is the data
visualization of the topic models. Without the description, it is a bit
unclear what the topics are about. Also, for the models divided by presidents
it would've been nicer to have the visualization in descending order of the
term with the highest frequency to term with the lowest frequency. A positive
of his project is that it seems incredibly unique, especially the part about
RoBama. Another con of his project is the repetition of many of the same
commands with different arguments. As I have been told, there is probably an
easier way to get the same result.

## Fatalities in Yemen's Civil War by Liz Masten

Masten's project was very interesting and I thought her visualizations of
Yemen's map were extremely insightful. One positive of their project was the
wide variety of event types they highlighted. One con is the inability to see
multiple event types within one map which would help see where multiple event
types are concentrated, if there is some relation with location. Similarly with
the fatalities by actor, I wish there was a way to see multiple actors at once
or show the event types inflicted by each actor. Another positive was that
they showed alternatives to the code that they had used.


